version: '3.7'
# for development, testing purposes only
# login via Globus will not work as this requires SSL and a dmoina registered withy Globus

services:

  db:
    image: mysql:8
    env_file: mysql.env
    volumes:
      - SAGE-UI-DB:/var/lib/mysql

  sage-ui:
    image: sagecontinuum/sage-ui
    build: .
    entrypoint: 
          - /testing-entrypoint.sh
    volumes:
        - ${PWD}/testing-entrypoint.sh:/testing-entrypoint.sh:ro
        - ${PWD}/app/:/usr/src/app
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file: mysql.env
    environment: 
      - Globus_Auth_Client_ID="${Globus_Auth_Client_ID}"
      - Globus_Auth_Client_Secret="${Globus_Auth_Client_Secret}"
      - ADD_USER="test,test"
      - DEBUG_VALUE=TRUE
volumes:
  SAGE-UI-DB:
